// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: business/proto/LogRecord.proto

package business.dto;

public final class LogRecordProto {
  private LogRecordProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum LogType
      implements com.google.protobuf.ProtocolMessageEnum {
    EXCEPTION_LOG(0, 1),
    ;
    
    public static final int EXCEPTION_LOG_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static LogType valueOf(int value) {
      switch (value) {
        case 1: return EXCEPTION_LOG;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<LogType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<LogType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LogType>() {
            public LogType findValueByNumber(int number) {
              return LogType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return business.dto.LogRecordProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final LogType[] VALUES = {
      EXCEPTION_LOG, 
    };
    
    public static LogType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private LogType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:business.proto.LogType)
  }
  
  public interface LogRecordOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string encrypt_user = 1;
    boolean hasEncryptUser();
    String getEncryptUser();
    
    // optional string locale = 2;
    boolean hasLocale();
    String getLocale();
    
    // optional string device = 3;
    boolean hasDevice();
    String getDevice();
    
    // optional string model = 4;
    boolean hasModel();
    String getModel();
    
    // optional string serial = 5;
    boolean hasSerial();
    String getSerial();
    
    // optional string build_type = 6;
    boolean hasBuildType();
    String getBuildType();
    
    // optional string release_version = 7;
    boolean hasReleaseVersion();
    String getReleaseVersion();
    
    // optional string incremental_version = 8;
    boolean hasIncrementalVersion();
    String getIncrementalVersion();
    
    // optional string build_flavor = 9;
    boolean hasBuildFlavor();
    String getBuildFlavor();
    
    // optional string tag = 10;
    boolean hasTag();
    String getTag();
    
    // optional string remixos_version = 11;
    boolean hasRemixosVersion();
    String getRemixosVersion();
    
    // optional string android_id = 12;
    boolean hasAndroidId();
    String getAndroidId();
    
    // optional int32 screen_width = 13;
    boolean hasScreenWidth();
    int getScreenWidth();
    
    // optional int32 screen_height = 14;
    boolean hasScreenHeight();
    int getScreenHeight();
    
    // optional int32 density = 15;
    boolean hasDensity();
    int getDensity();
    
    // optional int32 log_type = 16;
    boolean hasLogType();
    int getLogType();
    
    // optional .business.proto.Log log = 17;
    boolean hasLog();
    business.dto.LogRecordProto.Log getLog();
    business.dto.LogRecordProto.LogOrBuilder getLogOrBuilder();
  }
  public static final class LogRecord extends
      com.google.protobuf.GeneratedMessage
      implements LogRecordOrBuilder {
    // Use LogRecord.newBuilder() to construct.
    private LogRecord(Builder builder) {
      super(builder);
    }
    private LogRecord(boolean noInit) {}
    
    private static final LogRecord defaultInstance;
    public static LogRecord getDefaultInstance() {
      return defaultInstance;
    }
    
    public LogRecord getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return business.dto.LogRecordProto.internal_static_business_proto_LogRecord_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return business.dto.LogRecordProto.internal_static_business_proto_LogRecord_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string encrypt_user = 1;
    public static final int ENCRYPT_USER_FIELD_NUMBER = 1;
    private java.lang.Object encryptUser_;
    public boolean hasEncryptUser() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getEncryptUser() {
      java.lang.Object ref = encryptUser_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          encryptUser_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEncryptUserBytes() {
      java.lang.Object ref = encryptUser_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        encryptUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string locale = 2;
    public static final int LOCALE_FIELD_NUMBER = 2;
    private java.lang.Object locale_;
    public boolean hasLocale() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getLocale() {
      java.lang.Object ref = locale_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          locale_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLocaleBytes() {
      java.lang.Object ref = locale_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        locale_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string device = 3;
    public static final int DEVICE_FIELD_NUMBER = 3;
    private java.lang.Object device_;
    public boolean hasDevice() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDevice() {
      java.lang.Object ref = device_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          device_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDeviceBytes() {
      java.lang.Object ref = device_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        device_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string model = 4;
    public static final int MODEL_FIELD_NUMBER = 4;
    private java.lang.Object model_;
    public boolean hasModel() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getModel() {
      java.lang.Object ref = model_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          model_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string serial = 5;
    public static final int SERIAL_FIELD_NUMBER = 5;
    private java.lang.Object serial_;
    public boolean hasSerial() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getSerial() {
      java.lang.Object ref = serial_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          serial_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSerialBytes() {
      java.lang.Object ref = serial_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        serial_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string build_type = 6;
    public static final int BUILD_TYPE_FIELD_NUMBER = 6;
    private java.lang.Object buildType_;
    public boolean hasBuildType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getBuildType() {
      java.lang.Object ref = buildType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          buildType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBuildTypeBytes() {
      java.lang.Object ref = buildType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        buildType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string release_version = 7;
    public static final int RELEASE_VERSION_FIELD_NUMBER = 7;
    private java.lang.Object releaseVersion_;
    public boolean hasReleaseVersion() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getReleaseVersion() {
      java.lang.Object ref = releaseVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          releaseVersion_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getReleaseVersionBytes() {
      java.lang.Object ref = releaseVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        releaseVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string incremental_version = 8;
    public static final int INCREMENTAL_VERSION_FIELD_NUMBER = 8;
    private java.lang.Object incrementalVersion_;
    public boolean hasIncrementalVersion() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getIncrementalVersion() {
      java.lang.Object ref = incrementalVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          incrementalVersion_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIncrementalVersionBytes() {
      java.lang.Object ref = incrementalVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        incrementalVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string build_flavor = 9;
    public static final int BUILD_FLAVOR_FIELD_NUMBER = 9;
    private java.lang.Object buildFlavor_;
    public boolean hasBuildFlavor() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getBuildFlavor() {
      java.lang.Object ref = buildFlavor_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          buildFlavor_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBuildFlavorBytes() {
      java.lang.Object ref = buildFlavor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        buildFlavor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string tag = 10;
    public static final int TAG_FIELD_NUMBER = 10;
    private java.lang.Object tag_;
    public boolean hasTag() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getTag() {
      java.lang.Object ref = tag_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          tag_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTagBytes() {
      java.lang.Object ref = tag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        tag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string remixos_version = 11;
    public static final int REMIXOS_VERSION_FIELD_NUMBER = 11;
    private java.lang.Object remixosVersion_;
    public boolean hasRemixosVersion() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public String getRemixosVersion() {
      java.lang.Object ref = remixosVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          remixosVersion_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRemixosVersionBytes() {
      java.lang.Object ref = remixosVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        remixosVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string android_id = 12;
    public static final int ANDROID_ID_FIELD_NUMBER = 12;
    private java.lang.Object androidId_;
    public boolean hasAndroidId() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public String getAndroidId() {
      java.lang.Object ref = androidId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          androidId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAndroidIdBytes() {
      java.lang.Object ref = androidId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        androidId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 screen_width = 13;
    public static final int SCREEN_WIDTH_FIELD_NUMBER = 13;
    private int screenWidth_;
    public boolean hasScreenWidth() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public int getScreenWidth() {
      return screenWidth_;
    }
    
    // optional int32 screen_height = 14;
    public static final int SCREEN_HEIGHT_FIELD_NUMBER = 14;
    private int screenHeight_;
    public boolean hasScreenHeight() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public int getScreenHeight() {
      return screenHeight_;
    }
    
    // optional int32 density = 15;
    public static final int DENSITY_FIELD_NUMBER = 15;
    private int density_;
    public boolean hasDensity() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    public int getDensity() {
      return density_;
    }
    
    // optional int32 log_type = 16;
    public static final int LOG_TYPE_FIELD_NUMBER = 16;
    private int logType_;
    public boolean hasLogType() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    public int getLogType() {
      return logType_;
    }
    
    // optional .business.proto.Log log = 17;
    public static final int LOG_FIELD_NUMBER = 17;
    private business.dto.LogRecordProto.Log log_;
    public boolean hasLog() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    public business.dto.LogRecordProto.Log getLog() {
      return log_;
    }
    public business.dto.LogRecordProto.LogOrBuilder getLogOrBuilder() {
      return log_;
    }
    
    private void initFields() {
      encryptUser_ = "";
      locale_ = "";
      device_ = "";
      model_ = "";
      serial_ = "";
      buildType_ = "";
      releaseVersion_ = "";
      incrementalVersion_ = "";
      buildFlavor_ = "";
      tag_ = "";
      remixosVersion_ = "";
      androidId_ = "";
      screenWidth_ = 0;
      screenHeight_ = 0;
      density_ = 0;
      logType_ = 0;
      log_ = business.dto.LogRecordProto.Log.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (hasLog()) {
        if (!getLog().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getEncryptUserBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLocaleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDeviceBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getModelBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSerialBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getBuildTypeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getReleaseVersionBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getIncrementalVersionBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getBuildFlavorBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getTagBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getRemixosVersionBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getAndroidIdBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, screenWidth_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, screenHeight_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt32(15, density_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeInt32(16, logType_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeMessage(17, log_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getEncryptUserBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLocaleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDeviceBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getModelBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSerialBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getBuildTypeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getReleaseVersionBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getIncrementalVersionBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getBuildFlavorBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getTagBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getRemixosVersionBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getAndroidIdBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, screenWidth_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, screenHeight_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, density_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, logType_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(17, log_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static business.dto.LogRecordProto.LogRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static business.dto.LogRecordProto.LogRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static business.dto.LogRecordProto.LogRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static business.dto.LogRecordProto.LogRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static business.dto.LogRecordProto.LogRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static business.dto.LogRecordProto.LogRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static business.dto.LogRecordProto.LogRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static business.dto.LogRecordProto.LogRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static business.dto.LogRecordProto.LogRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static business.dto.LogRecordProto.LogRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(business.dto.LogRecordProto.LogRecord prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements business.dto.LogRecordProto.LogRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return business.dto.LogRecordProto.internal_static_business_proto_LogRecord_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return business.dto.LogRecordProto.internal_static_business_proto_LogRecord_fieldAccessorTable;
      }
      
      // Construct using business.dto.LogRecordProto.LogRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLogFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        encryptUser_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        locale_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        device_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        model_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        serial_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        buildType_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        releaseVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        incrementalVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        buildFlavor_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        tag_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        remixosVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        androidId_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        screenWidth_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        screenHeight_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        density_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        logType_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        if (logBuilder_ == null) {
          log_ = business.dto.LogRecordProto.Log.getDefaultInstance();
        } else {
          logBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return business.dto.LogRecordProto.LogRecord.getDescriptor();
      }
      
      public business.dto.LogRecordProto.LogRecord getDefaultInstanceForType() {
        return business.dto.LogRecordProto.LogRecord.getDefaultInstance();
      }
      
      public business.dto.LogRecordProto.LogRecord build() {
        business.dto.LogRecordProto.LogRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private business.dto.LogRecordProto.LogRecord buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        business.dto.LogRecordProto.LogRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public business.dto.LogRecordProto.LogRecord buildPartial() {
        business.dto.LogRecordProto.LogRecord result = new business.dto.LogRecordProto.LogRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.encryptUser_ = encryptUser_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.locale_ = locale_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.device_ = device_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.model_ = model_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.serial_ = serial_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.buildType_ = buildType_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.releaseVersion_ = releaseVersion_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.incrementalVersion_ = incrementalVersion_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.buildFlavor_ = buildFlavor_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.tag_ = tag_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.remixosVersion_ = remixosVersion_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.androidId_ = androidId_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.screenWidth_ = screenWidth_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.screenHeight_ = screenHeight_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.density_ = density_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.logType_ = logType_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        if (logBuilder_ == null) {
          result.log_ = log_;
        } else {
          result.log_ = logBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof business.dto.LogRecordProto.LogRecord) {
          return mergeFrom((business.dto.LogRecordProto.LogRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(business.dto.LogRecordProto.LogRecord other) {
        if (other == business.dto.LogRecordProto.LogRecord.getDefaultInstance()) return this;
        if (other.hasEncryptUser()) {
          setEncryptUser(other.getEncryptUser());
        }
        if (other.hasLocale()) {
          setLocale(other.getLocale());
        }
        if (other.hasDevice()) {
          setDevice(other.getDevice());
        }
        if (other.hasModel()) {
          setModel(other.getModel());
        }
        if (other.hasSerial()) {
          setSerial(other.getSerial());
        }
        if (other.hasBuildType()) {
          setBuildType(other.getBuildType());
        }
        if (other.hasReleaseVersion()) {
          setReleaseVersion(other.getReleaseVersion());
        }
        if (other.hasIncrementalVersion()) {
          setIncrementalVersion(other.getIncrementalVersion());
        }
        if (other.hasBuildFlavor()) {
          setBuildFlavor(other.getBuildFlavor());
        }
        if (other.hasTag()) {
          setTag(other.getTag());
        }
        if (other.hasRemixosVersion()) {
          setRemixosVersion(other.getRemixosVersion());
        }
        if (other.hasAndroidId()) {
          setAndroidId(other.getAndroidId());
        }
        if (other.hasScreenWidth()) {
          setScreenWidth(other.getScreenWidth());
        }
        if (other.hasScreenHeight()) {
          setScreenHeight(other.getScreenHeight());
        }
        if (other.hasDensity()) {
          setDensity(other.getDensity());
        }
        if (other.hasLogType()) {
          setLogType(other.getLogType());
        }
        if (other.hasLog()) {
          mergeLog(other.getLog());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (hasLog()) {
          if (!getLog().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              encryptUser_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              locale_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              device_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              model_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              serial_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              buildType_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              releaseVersion_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              incrementalVersion_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              buildFlavor_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              tag_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              remixosVersion_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              androidId_ = input.readBytes();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              screenWidth_ = input.readInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              screenHeight_ = input.readInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              density_ = input.readInt32();
              break;
            }
            case 128: {
              bitField0_ |= 0x00008000;
              logType_ = input.readInt32();
              break;
            }
            case 138: {
              business.dto.LogRecordProto.Log.Builder subBuilder = business.dto.LogRecordProto.Log.newBuilder();
              if (hasLog()) {
                subBuilder.mergeFrom(getLog());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLog(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string encrypt_user = 1;
      private java.lang.Object encryptUser_ = "";
      public boolean hasEncryptUser() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getEncryptUser() {
        java.lang.Object ref = encryptUser_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          encryptUser_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEncryptUser(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        encryptUser_ = value;
        onChanged();
        return this;
      }
      public Builder clearEncryptUser() {
        bitField0_ = (bitField0_ & ~0x00000001);
        encryptUser_ = getDefaultInstance().getEncryptUser();
        onChanged();
        return this;
      }
      void setEncryptUser(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        encryptUser_ = value;
        onChanged();
      }
      
      // optional string locale = 2;
      private java.lang.Object locale_ = "";
      public boolean hasLocale() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getLocale() {
        java.lang.Object ref = locale_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          locale_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLocale(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        locale_ = value;
        onChanged();
        return this;
      }
      public Builder clearLocale() {
        bitField0_ = (bitField0_ & ~0x00000002);
        locale_ = getDefaultInstance().getLocale();
        onChanged();
        return this;
      }
      void setLocale(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        locale_ = value;
        onChanged();
      }
      
      // optional string device = 3;
      private java.lang.Object device_ = "";
      public boolean hasDevice() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDevice() {
        java.lang.Object ref = device_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          device_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDevice(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        device_ = value;
        onChanged();
        return this;
      }
      public Builder clearDevice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        device_ = getDefaultInstance().getDevice();
        onChanged();
        return this;
      }
      void setDevice(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        device_ = value;
        onChanged();
      }
      
      // optional string model = 4;
      private java.lang.Object model_ = "";
      public boolean hasModel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getModel() {
        java.lang.Object ref = model_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          model_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setModel(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        model_ = value;
        onChanged();
        return this;
      }
      public Builder clearModel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        model_ = getDefaultInstance().getModel();
        onChanged();
        return this;
      }
      void setModel(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        model_ = value;
        onChanged();
      }
      
      // optional string serial = 5;
      private java.lang.Object serial_ = "";
      public boolean hasSerial() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getSerial() {
        java.lang.Object ref = serial_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          serial_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSerial(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        serial_ = value;
        onChanged();
        return this;
      }
      public Builder clearSerial() {
        bitField0_ = (bitField0_ & ~0x00000010);
        serial_ = getDefaultInstance().getSerial();
        onChanged();
        return this;
      }
      void setSerial(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        serial_ = value;
        onChanged();
      }
      
      // optional string build_type = 6;
      private java.lang.Object buildType_ = "";
      public boolean hasBuildType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getBuildType() {
        java.lang.Object ref = buildType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          buildType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBuildType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        buildType_ = value;
        onChanged();
        return this;
      }
      public Builder clearBuildType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        buildType_ = getDefaultInstance().getBuildType();
        onChanged();
        return this;
      }
      void setBuildType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        buildType_ = value;
        onChanged();
      }
      
      // optional string release_version = 7;
      private java.lang.Object releaseVersion_ = "";
      public boolean hasReleaseVersion() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getReleaseVersion() {
        java.lang.Object ref = releaseVersion_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          releaseVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setReleaseVersion(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        releaseVersion_ = value;
        onChanged();
        return this;
      }
      public Builder clearReleaseVersion() {
        bitField0_ = (bitField0_ & ~0x00000040);
        releaseVersion_ = getDefaultInstance().getReleaseVersion();
        onChanged();
        return this;
      }
      void setReleaseVersion(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        releaseVersion_ = value;
        onChanged();
      }
      
      // optional string incremental_version = 8;
      private java.lang.Object incrementalVersion_ = "";
      public boolean hasIncrementalVersion() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getIncrementalVersion() {
        java.lang.Object ref = incrementalVersion_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          incrementalVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIncrementalVersion(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        incrementalVersion_ = value;
        onChanged();
        return this;
      }
      public Builder clearIncrementalVersion() {
        bitField0_ = (bitField0_ & ~0x00000080);
        incrementalVersion_ = getDefaultInstance().getIncrementalVersion();
        onChanged();
        return this;
      }
      void setIncrementalVersion(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        incrementalVersion_ = value;
        onChanged();
      }
      
      // optional string build_flavor = 9;
      private java.lang.Object buildFlavor_ = "";
      public boolean hasBuildFlavor() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getBuildFlavor() {
        java.lang.Object ref = buildFlavor_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          buildFlavor_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBuildFlavor(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        buildFlavor_ = value;
        onChanged();
        return this;
      }
      public Builder clearBuildFlavor() {
        bitField0_ = (bitField0_ & ~0x00000100);
        buildFlavor_ = getDefaultInstance().getBuildFlavor();
        onChanged();
        return this;
      }
      void setBuildFlavor(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        buildFlavor_ = value;
        onChanged();
      }
      
      // optional string tag = 10;
      private java.lang.Object tag_ = "";
      public boolean hasTag() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getTag() {
        java.lang.Object ref = tag_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          tag_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTag(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        tag_ = value;
        onChanged();
        return this;
      }
      public Builder clearTag() {
        bitField0_ = (bitField0_ & ~0x00000200);
        tag_ = getDefaultInstance().getTag();
        onChanged();
        return this;
      }
      void setTag(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        tag_ = value;
        onChanged();
      }
      
      // optional string remixos_version = 11;
      private java.lang.Object remixosVersion_ = "";
      public boolean hasRemixosVersion() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public String getRemixosVersion() {
        java.lang.Object ref = remixosVersion_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          remixosVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRemixosVersion(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        remixosVersion_ = value;
        onChanged();
        return this;
      }
      public Builder clearRemixosVersion() {
        bitField0_ = (bitField0_ & ~0x00000400);
        remixosVersion_ = getDefaultInstance().getRemixosVersion();
        onChanged();
        return this;
      }
      void setRemixosVersion(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000400;
        remixosVersion_ = value;
        onChanged();
      }
      
      // optional string android_id = 12;
      private java.lang.Object androidId_ = "";
      public boolean hasAndroidId() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public String getAndroidId() {
        java.lang.Object ref = androidId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          androidId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAndroidId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        androidId_ = value;
        onChanged();
        return this;
      }
      public Builder clearAndroidId() {
        bitField0_ = (bitField0_ & ~0x00000800);
        androidId_ = getDefaultInstance().getAndroidId();
        onChanged();
        return this;
      }
      void setAndroidId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000800;
        androidId_ = value;
        onChanged();
      }
      
      // optional int32 screen_width = 13;
      private int screenWidth_ ;
      public boolean hasScreenWidth() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public int getScreenWidth() {
        return screenWidth_;
      }
      public Builder setScreenWidth(int value) {
        bitField0_ |= 0x00001000;
        screenWidth_ = value;
        onChanged();
        return this;
      }
      public Builder clearScreenWidth() {
        bitField0_ = (bitField0_ & ~0x00001000);
        screenWidth_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 screen_height = 14;
      private int screenHeight_ ;
      public boolean hasScreenHeight() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public int getScreenHeight() {
        return screenHeight_;
      }
      public Builder setScreenHeight(int value) {
        bitField0_ |= 0x00002000;
        screenHeight_ = value;
        onChanged();
        return this;
      }
      public Builder clearScreenHeight() {
        bitField0_ = (bitField0_ & ~0x00002000);
        screenHeight_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 density = 15;
      private int density_ ;
      public boolean hasDensity() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      public int getDensity() {
        return density_;
      }
      public Builder setDensity(int value) {
        bitField0_ |= 0x00004000;
        density_ = value;
        onChanged();
        return this;
      }
      public Builder clearDensity() {
        bitField0_ = (bitField0_ & ~0x00004000);
        density_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 log_type = 16;
      private int logType_ ;
      public boolean hasLogType() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      public int getLogType() {
        return logType_;
      }
      public Builder setLogType(int value) {
        bitField0_ |= 0x00008000;
        logType_ = value;
        onChanged();
        return this;
      }
      public Builder clearLogType() {
        bitField0_ = (bitField0_ & ~0x00008000);
        logType_ = 0;
        onChanged();
        return this;
      }
      
      // optional .business.proto.Log log = 17;
      private business.dto.LogRecordProto.Log log_ = business.dto.LogRecordProto.Log.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          business.dto.LogRecordProto.Log, business.dto.LogRecordProto.Log.Builder, business.dto.LogRecordProto.LogOrBuilder> logBuilder_;
      public boolean hasLog() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      public business.dto.LogRecordProto.Log getLog() {
        if (logBuilder_ == null) {
          return log_;
        } else {
          return logBuilder_.getMessage();
        }
      }
      public Builder setLog(business.dto.LogRecordProto.Log value) {
        if (logBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          log_ = value;
          onChanged();
        } else {
          logBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00010000;
        return this;
      }
      public Builder setLog(
          business.dto.LogRecordProto.Log.Builder builderForValue) {
        if (logBuilder_ == null) {
          log_ = builderForValue.build();
          onChanged();
        } else {
          logBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00010000;
        return this;
      }
      public Builder mergeLog(business.dto.LogRecordProto.Log value) {
        if (logBuilder_ == null) {
          if (((bitField0_ & 0x00010000) == 0x00010000) &&
              log_ != business.dto.LogRecordProto.Log.getDefaultInstance()) {
            log_ =
              business.dto.LogRecordProto.Log.newBuilder(log_).mergeFrom(value).buildPartial();
          } else {
            log_ = value;
          }
          onChanged();
        } else {
          logBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00010000;
        return this;
      }
      public Builder clearLog() {
        if (logBuilder_ == null) {
          log_ = business.dto.LogRecordProto.Log.getDefaultInstance();
          onChanged();
        } else {
          logBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }
      public business.dto.LogRecordProto.Log.Builder getLogBuilder() {
        bitField0_ |= 0x00010000;
        onChanged();
        return getLogFieldBuilder().getBuilder();
      }
      public business.dto.LogRecordProto.LogOrBuilder getLogOrBuilder() {
        if (logBuilder_ != null) {
          return logBuilder_.getMessageOrBuilder();
        } else {
          return log_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          business.dto.LogRecordProto.Log, business.dto.LogRecordProto.Log.Builder, business.dto.LogRecordProto.LogOrBuilder> 
          getLogFieldBuilder() {
        if (logBuilder_ == null) {
          logBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              business.dto.LogRecordProto.Log, business.dto.LogRecordProto.Log.Builder, business.dto.LogRecordProto.LogOrBuilder>(
                  log_,
                  getParentForChildren(),
                  isClean());
          log_ = null;
        }
        return logBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:business.proto.LogRecord)
    }
    
    static {
      defaultInstance = new LogRecord(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:business.proto.LogRecord)
  }
  
  public interface LogOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .business.proto.ExceptionLog exceptionLog = 1;
    boolean hasExceptionLog();
    business.dto.LogRecordProto.ExceptionLog getExceptionLog();
    business.dto.LogRecordProto.ExceptionLogOrBuilder getExceptionLogOrBuilder();
  }
  public static final class Log extends
      com.google.protobuf.GeneratedMessage
      implements LogOrBuilder {
    // Use Log.newBuilder() to construct.
    private Log(Builder builder) {
      super(builder);
    }
    private Log(boolean noInit) {}
    
    private static final Log defaultInstance;
    public static Log getDefaultInstance() {
      return defaultInstance;
    }
    
    public Log getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return business.dto.LogRecordProto.internal_static_business_proto_Log_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return business.dto.LogRecordProto.internal_static_business_proto_Log_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .business.proto.ExceptionLog exceptionLog = 1;
    public static final int EXCEPTIONLOG_FIELD_NUMBER = 1;
    private business.dto.LogRecordProto.ExceptionLog exceptionLog_;
    public boolean hasExceptionLog() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public business.dto.LogRecordProto.ExceptionLog getExceptionLog() {
      return exceptionLog_;
    }
    public business.dto.LogRecordProto.ExceptionLogOrBuilder getExceptionLogOrBuilder() {
      return exceptionLog_;
    }
    
    private void initFields() {
      exceptionLog_ = business.dto.LogRecordProto.ExceptionLog.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (hasExceptionLog()) {
        if (!getExceptionLog().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, exceptionLog_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, exceptionLog_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static business.dto.LogRecordProto.Log parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static business.dto.LogRecordProto.Log parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static business.dto.LogRecordProto.Log parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static business.dto.LogRecordProto.Log parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static business.dto.LogRecordProto.Log parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static business.dto.LogRecordProto.Log parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static business.dto.LogRecordProto.Log parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static business.dto.LogRecordProto.Log parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static business.dto.LogRecordProto.Log parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static business.dto.LogRecordProto.Log parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(business.dto.LogRecordProto.Log prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements business.dto.LogRecordProto.LogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return business.dto.LogRecordProto.internal_static_business_proto_Log_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return business.dto.LogRecordProto.internal_static_business_proto_Log_fieldAccessorTable;
      }
      
      // Construct using business.dto.LogRecordProto.Log.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getExceptionLogFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (exceptionLogBuilder_ == null) {
          exceptionLog_ = business.dto.LogRecordProto.ExceptionLog.getDefaultInstance();
        } else {
          exceptionLogBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return business.dto.LogRecordProto.Log.getDescriptor();
      }
      
      public business.dto.LogRecordProto.Log getDefaultInstanceForType() {
        return business.dto.LogRecordProto.Log.getDefaultInstance();
      }
      
      public business.dto.LogRecordProto.Log build() {
        business.dto.LogRecordProto.Log result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private business.dto.LogRecordProto.Log buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        business.dto.LogRecordProto.Log result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public business.dto.LogRecordProto.Log buildPartial() {
        business.dto.LogRecordProto.Log result = new business.dto.LogRecordProto.Log(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (exceptionLogBuilder_ == null) {
          result.exceptionLog_ = exceptionLog_;
        } else {
          result.exceptionLog_ = exceptionLogBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof business.dto.LogRecordProto.Log) {
          return mergeFrom((business.dto.LogRecordProto.Log)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(business.dto.LogRecordProto.Log other) {
        if (other == business.dto.LogRecordProto.Log.getDefaultInstance()) return this;
        if (other.hasExceptionLog()) {
          mergeExceptionLog(other.getExceptionLog());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (hasExceptionLog()) {
          if (!getExceptionLog().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              business.dto.LogRecordProto.ExceptionLog.Builder subBuilder = business.dto.LogRecordProto.ExceptionLog.newBuilder();
              if (hasExceptionLog()) {
                subBuilder.mergeFrom(getExceptionLog());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setExceptionLog(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .business.proto.ExceptionLog exceptionLog = 1;
      private business.dto.LogRecordProto.ExceptionLog exceptionLog_ = business.dto.LogRecordProto.ExceptionLog.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          business.dto.LogRecordProto.ExceptionLog, business.dto.LogRecordProto.ExceptionLog.Builder, business.dto.LogRecordProto.ExceptionLogOrBuilder> exceptionLogBuilder_;
      public boolean hasExceptionLog() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public business.dto.LogRecordProto.ExceptionLog getExceptionLog() {
        if (exceptionLogBuilder_ == null) {
          return exceptionLog_;
        } else {
          return exceptionLogBuilder_.getMessage();
        }
      }
      public Builder setExceptionLog(business.dto.LogRecordProto.ExceptionLog value) {
        if (exceptionLogBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          exceptionLog_ = value;
          onChanged();
        } else {
          exceptionLogBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setExceptionLog(
          business.dto.LogRecordProto.ExceptionLog.Builder builderForValue) {
        if (exceptionLogBuilder_ == null) {
          exceptionLog_ = builderForValue.build();
          onChanged();
        } else {
          exceptionLogBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeExceptionLog(business.dto.LogRecordProto.ExceptionLog value) {
        if (exceptionLogBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              exceptionLog_ != business.dto.LogRecordProto.ExceptionLog.getDefaultInstance()) {
            exceptionLog_ =
              business.dto.LogRecordProto.ExceptionLog.newBuilder(exceptionLog_).mergeFrom(value).buildPartial();
          } else {
            exceptionLog_ = value;
          }
          onChanged();
        } else {
          exceptionLogBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearExceptionLog() {
        if (exceptionLogBuilder_ == null) {
          exceptionLog_ = business.dto.LogRecordProto.ExceptionLog.getDefaultInstance();
          onChanged();
        } else {
          exceptionLogBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public business.dto.LogRecordProto.ExceptionLog.Builder getExceptionLogBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getExceptionLogFieldBuilder().getBuilder();
      }
      public business.dto.LogRecordProto.ExceptionLogOrBuilder getExceptionLogOrBuilder() {
        if (exceptionLogBuilder_ != null) {
          return exceptionLogBuilder_.getMessageOrBuilder();
        } else {
          return exceptionLog_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          business.dto.LogRecordProto.ExceptionLog, business.dto.LogRecordProto.ExceptionLog.Builder, business.dto.LogRecordProto.ExceptionLogOrBuilder> 
          getExceptionLogFieldBuilder() {
        if (exceptionLogBuilder_ == null) {
          exceptionLogBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              business.dto.LogRecordProto.ExceptionLog, business.dto.LogRecordProto.ExceptionLog.Builder, business.dto.LogRecordProto.ExceptionLogOrBuilder>(
                  exceptionLog_,
                  getParentForChildren(),
                  isClean());
          exceptionLog_ = null;
        }
        return exceptionLogBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:business.proto.Log)
    }
    
    static {
      defaultInstance = new Log(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:business.proto.Log)
  }
  
  public interface ExceptionLogOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string exception = 1;
    boolean hasException();
    String getException();
    
    // required string detail = 2;
    boolean hasDetail();
    String getDetail();
  }
  public static final class ExceptionLog extends
      com.google.protobuf.GeneratedMessage
      implements ExceptionLogOrBuilder {
    // Use ExceptionLog.newBuilder() to construct.
    private ExceptionLog(Builder builder) {
      super(builder);
    }
    private ExceptionLog(boolean noInit) {}
    
    private static final ExceptionLog defaultInstance;
    public static ExceptionLog getDefaultInstance() {
      return defaultInstance;
    }
    
    public ExceptionLog getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return business.dto.LogRecordProto.internal_static_business_proto_ExceptionLog_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return business.dto.LogRecordProto.internal_static_business_proto_ExceptionLog_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string exception = 1;
    public static final int EXCEPTION_FIELD_NUMBER = 1;
    private java.lang.Object exception_;
    public boolean hasException() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getException() {
      java.lang.Object ref = exception_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          exception_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getExceptionBytes() {
      java.lang.Object ref = exception_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        exception_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string detail = 2;
    public static final int DETAIL_FIELD_NUMBER = 2;
    private java.lang.Object detail_;
    public boolean hasDetail() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getDetail() {
      java.lang.Object ref = detail_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          detail_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDetailBytes() {
      java.lang.Object ref = detail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        detail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      exception_ = "";
      detail_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasException()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDetail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getExceptionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDetailBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getExceptionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDetailBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static business.dto.LogRecordProto.ExceptionLog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static business.dto.LogRecordProto.ExceptionLog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static business.dto.LogRecordProto.ExceptionLog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static business.dto.LogRecordProto.ExceptionLog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static business.dto.LogRecordProto.ExceptionLog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static business.dto.LogRecordProto.ExceptionLog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static business.dto.LogRecordProto.ExceptionLog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static business.dto.LogRecordProto.ExceptionLog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static business.dto.LogRecordProto.ExceptionLog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static business.dto.LogRecordProto.ExceptionLog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(business.dto.LogRecordProto.ExceptionLog prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements business.dto.LogRecordProto.ExceptionLogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return business.dto.LogRecordProto.internal_static_business_proto_ExceptionLog_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return business.dto.LogRecordProto.internal_static_business_proto_ExceptionLog_fieldAccessorTable;
      }
      
      // Construct using business.dto.LogRecordProto.ExceptionLog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        exception_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        detail_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return business.dto.LogRecordProto.ExceptionLog.getDescriptor();
      }
      
      public business.dto.LogRecordProto.ExceptionLog getDefaultInstanceForType() {
        return business.dto.LogRecordProto.ExceptionLog.getDefaultInstance();
      }
      
      public business.dto.LogRecordProto.ExceptionLog build() {
        business.dto.LogRecordProto.ExceptionLog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private business.dto.LogRecordProto.ExceptionLog buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        business.dto.LogRecordProto.ExceptionLog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public business.dto.LogRecordProto.ExceptionLog buildPartial() {
        business.dto.LogRecordProto.ExceptionLog result = new business.dto.LogRecordProto.ExceptionLog(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.exception_ = exception_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.detail_ = detail_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof business.dto.LogRecordProto.ExceptionLog) {
          return mergeFrom((business.dto.LogRecordProto.ExceptionLog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(business.dto.LogRecordProto.ExceptionLog other) {
        if (other == business.dto.LogRecordProto.ExceptionLog.getDefaultInstance()) return this;
        if (other.hasException()) {
          setException(other.getException());
        }
        if (other.hasDetail()) {
          setDetail(other.getDetail());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasException()) {
          
          return false;
        }
        if (!hasDetail()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              exception_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              detail_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string exception = 1;
      private java.lang.Object exception_ = "";
      public boolean hasException() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getException() {
        java.lang.Object ref = exception_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          exception_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setException(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        exception_ = value;
        onChanged();
        return this;
      }
      public Builder clearException() {
        bitField0_ = (bitField0_ & ~0x00000001);
        exception_ = getDefaultInstance().getException();
        onChanged();
        return this;
      }
      void setException(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        exception_ = value;
        onChanged();
      }
      
      // required string detail = 2;
      private java.lang.Object detail_ = "";
      public boolean hasDetail() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getDetail() {
        java.lang.Object ref = detail_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          detail_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDetail(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        detail_ = value;
        onChanged();
        return this;
      }
      public Builder clearDetail() {
        bitField0_ = (bitField0_ & ~0x00000002);
        detail_ = getDefaultInstance().getDetail();
        onChanged();
        return this;
      }
      void setDetail(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        detail_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:business.proto.ExceptionLog)
    }
    
    static {
      defaultInstance = new ExceptionLog(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:business.proto.ExceptionLog)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_business_proto_LogRecord_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_business_proto_LogRecord_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_business_proto_Log_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_business_proto_Log_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_business_proto_ExceptionLog_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_business_proto_ExceptionLog_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036business/proto/LogRecord.proto\022\016busine" +
      "ss.proto\"\354\002\n\tLogRecord\022\024\n\014encrypt_user\030\001" +
      " \001(\t\022\016\n\006locale\030\002 \001(\t\022\016\n\006device\030\003 \001(\t\022\r\n\005" +
      "model\030\004 \001(\t\022\016\n\006serial\030\005 \001(\t\022\022\n\nbuild_typ" +
      "e\030\006 \001(\t\022\027\n\017release_version\030\007 \001(\t\022\033\n\023incr" +
      "emental_version\030\010 \001(\t\022\024\n\014build_flavor\030\t " +
      "\001(\t\022\013\n\003tag\030\n \001(\t\022\027\n\017remixos_version\030\013 \001(" +
      "\t\022\022\n\nandroid_id\030\014 \001(\t\022\024\n\014screen_width\030\r " +
      "\001(\005\022\025\n\rscreen_height\030\016 \001(\005\022\017\n\007density\030\017 " +
      "\001(\005\022\020\n\010log_type\030\020 \001(\005\022 \n\003log\030\021 \001(\0132\023.bus",
      "iness.proto.Log\"9\n\003Log\0222\n\014exceptionLog\030\001" +
      " \001(\0132\034.business.proto.ExceptionLog\"1\n\014Ex" +
      "ceptionLog\022\021\n\texception\030\001 \002(\t\022\016\n\006detail\030" +
      "\002 \002(\t*\034\n\007LogType\022\021\n\rEXCEPTION_LOG\020\001B\036\n\014b" +
      "usiness.dtoB\016LogRecordProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_business_proto_LogRecord_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_business_proto_LogRecord_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_business_proto_LogRecord_descriptor,
              new java.lang.String[] { "EncryptUser", "Locale", "Device", "Model", "Serial", "BuildType", "ReleaseVersion", "IncrementalVersion", "BuildFlavor", "Tag", "RemixosVersion", "AndroidId", "ScreenWidth", "ScreenHeight", "Density", "LogType", "Log", },
              business.dto.LogRecordProto.LogRecord.class,
              business.dto.LogRecordProto.LogRecord.Builder.class);
          internal_static_business_proto_Log_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_business_proto_Log_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_business_proto_Log_descriptor,
              new java.lang.String[] { "ExceptionLog", },
              business.dto.LogRecordProto.Log.class,
              business.dto.LogRecordProto.Log.Builder.class);
          internal_static_business_proto_ExceptionLog_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_business_proto_ExceptionLog_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_business_proto_ExceptionLog_descriptor,
              new java.lang.String[] { "Exception", "Detail", },
              business.dto.LogRecordProto.ExceptionLog.class,
              business.dto.LogRecordProto.ExceptionLog.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
